### ISSUE TITLE
Questions about "gen_pts.py"

### ISSUE THREAD

**Issue by GalaxyWM** [DC1991/FS_Net#3]
Thanks for ur project and paper. 
there're some questions about data preprocess file "gen_pts.py". what does the 'path' in this file refer to?  there may be no '.ply' modle files after generating annos. so could you give more information about it?
btw,  what's the purpose of this preprocess? I don't quite understand BOP
thanks  ∩_∩

**Comment by DC1991** [comment]
the 'path' is the path of your object model which should be '.ply' file (you need to transfer the '.obj' file to '.ply' file, you can search on the internet, there are many options for this). The preprocess makes the data easy to read and get the 6D pose of the training set (since the original NOCS dataset does not provide the 6D pose directly).

**Comment by GalaxyWM** [comment]
thx for your reply!!!    sry, I didn't write clear the last question. I refer to the purpose of 'gen_pts.py'.  it seems that no file is created according to the code.

**Comment by DC1991** [comment]
Please check your save path and file name.

**Comment by Jierui-Liu** [comment]
> thx for your reply!!! sry, I didn't write clear the last question. I refer to the purpose of 'gen_pts.py'. it seems that no file is created according to the code.

I find the same problem and did you solve it?

**Comment by rohanksaxena** [comment]
Has anyone been able to figure this problem out? The main function is calling only the renderer. I am not sure how to use the "get_one" and "get_point_wise_lab" methods.
